name: mnemonicorum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-196.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.4
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^13.2.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/formulas/
