name: mnemonicorum
description: "An interactive Flutter application for learning mathematical formulas through engaging practice sessions, progress tracking, and gamified learning experiences."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-196.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.4
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^16.0.0
  auto_size_text: ^3.0.0
  firebase_core: ^3.1.1
  firebase_ai: ^2.2.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.6.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/formulas/
    - assets/prompts/
